#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinema_Projesi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sinema")]
	public partial class Sinema_VTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFilm(Film instance);
    partial void UpdateFilm(Film instance);
    partial void DeleteFilm(Film instance);
    partial void InsertFilmYayin(FilmYayin instance);
    partial void UpdateFilmYayin(FilmYayin instance);
    partial void DeleteFilmYayin(FilmYayin instance);
    partial void InsertSalon(Salon instance);
    partial void UpdateSalon(Salon instance);
    partial void DeleteSalon(Salon instance);
    #endregion
		
		public Sinema_VTDataContext() : 
				base(global::Sinema_Projesi.Properties.Settings.Default.SinemaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Sinema_VTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sinema_VTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sinema_VTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Sinema_VTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Film> Films
		{
			get
			{
				return this.GetTable<Film>();
			}
		}
		
		public System.Data.Linq.Table<FilmYayin> FilmYayins
		{
			get
			{
				return this.GetTable<FilmYayin>();
			}
		}
		
		public System.Data.Linq.Table<Salon> Salons
		{
			get
			{
				return this.GetTable<Salon>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Film")]
	public partial class Film : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _FilmID;
		
		private string _FilmAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFilmIDChanging(short value);
    partial void OnFilmIDChanged();
    partial void OnFilmAdiChanging(string value);
    partial void OnFilmAdiChanged();
    #endregion
		
		public Film()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmID", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short FilmID
		{
			get
			{
				return this._FilmID;
			}
			set
			{
				if ((this._FilmID != value))
				{
					this.OnFilmIDChanging(value);
					this.SendPropertyChanging();
					this._FilmID = value;
					this.SendPropertyChanged("FilmID");
					this.OnFilmIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FilmAdi
		{
			get
			{
				return this._FilmAdi;
			}
			set
			{
				if ((this._FilmAdi != value))
				{
					this.OnFilmAdiChanging(value);
					this.SendPropertyChanging();
					this._FilmAdi = value;
					this.SendPropertyChanged("FilmAdi");
					this.OnFilmAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FilmYayin")]
	public partial class FilmYayin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _FYID;
		
		private short _FilmID;
		
		private short _SalonID;
		
		private System.DateTime _FYZaman;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFYIDChanging(short value);
    partial void OnFYIDChanged();
    partial void OnFilmIDChanging(short value);
    partial void OnFilmIDChanged();
    partial void OnSalonIDChanging(short value);
    partial void OnSalonIDChanged();
    partial void OnFYZamanChanging(System.DateTime value);
    partial void OnFYZamanChanged();
    #endregion
		
		public FilmYayin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FYID", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short FYID
		{
			get
			{
				return this._FYID;
			}
			set
			{
				if ((this._FYID != value))
				{
					this.OnFYIDChanging(value);
					this.SendPropertyChanging();
					this._FYID = value;
					this.SendPropertyChanged("FYID");
					this.OnFYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilmID", DbType="SmallInt NOT NULL")]
		public short FilmID
		{
			get
			{
				return this._FilmID;
			}
			set
			{
				if ((this._FilmID != value))
				{
					this.OnFilmIDChanging(value);
					this.SendPropertyChanging();
					this._FilmID = value;
					this.SendPropertyChanged("FilmID");
					this.OnFilmIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonID", DbType="SmallInt NOT NULL")]
		public short SalonID
		{
			get
			{
				return this._SalonID;
			}
			set
			{
				if ((this._SalonID != value))
				{
					this.OnSalonIDChanging(value);
					this.SendPropertyChanging();
					this._SalonID = value;
					this.SendPropertyChanged("SalonID");
					this.OnSalonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FYZaman", DbType="Date NOT NULL")]
		public System.DateTime FYZaman
		{
			get
			{
				return this._FYZaman;
			}
			set
			{
				if ((this._FYZaman != value))
				{
					this.OnFYZamanChanging(value);
					this.SendPropertyChanging();
					this._FYZaman = value;
					this.SendPropertyChanged("FYZaman");
					this.OnFYZamanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Salon")]
	public partial class Salon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _SalonID;
		
		private string _SalonAdi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSalonIDChanging(short value);
    partial void OnSalonIDChanged();
    partial void OnSalonAdiChanging(string value);
    partial void OnSalonAdiChanged();
    #endregion
		
		public Salon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonID", AutoSync=AutoSync.Always, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short SalonID
		{
			get
			{
				return this._SalonID;
			}
			set
			{
				if ((this._SalonID != value))
				{
					this.OnSalonIDChanging(value);
					this.SendPropertyChanging();
					this._SalonID = value;
					this.SendPropertyChanged("SalonID");
					this.OnSalonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalonAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SalonAdi
		{
			get
			{
				return this._SalonAdi;
			}
			set
			{
				if ((this._SalonAdi != value))
				{
					this.OnSalonAdiChanging(value);
					this.SendPropertyChanging();
					this._SalonAdi = value;
					this.SendPropertyChanged("SalonAdi");
					this.OnSalonAdiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
